---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    pgp: >-
      01CF49B023FA95951E7B2B0A1A72E18A2ECFB83F
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: >-
      BF06DD9C21E3BF4384FCC425D15E12B67F66DA26,
      01CF49B023FA95951E7B2B0A1A72E18A2ECFB83F
