---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1fv2r9xcluc5vnp4l8yg5amr95ar2vaencq5mddfead9lmrjx8fpqc8994x
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1fv2r9xcluc5vnp4l8yg5amr95ar2vaencq5mddfead9lmrjx8fpqc8994x

# find ./cluster -type f -iname "*sops*" -exec sops --decrypt --in-place {} \;
# find ./cluster -type f -iname "*sops*" -exec sops --encrypt --in-place {} \;
