# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7BmqwSia6WZngHh5wXbqXXV2vhqC/mvYSQ==,iv:IGzOBiCurGFx9oXk4ICdYBvPv2APL7oj1+yxiDGPcPE=,tag:Ga5KisqitUcIXC+TIr6bDQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:sEUKQ9boNy2j/FTUJCMJTtghBhx+/1MdfhvcHuFafP8mrkUAvg==,iv:CIm5QZfeEpjvSwGgw9l//um7ltC41ar1yBdqeAeOUAU=,tag:k9eRpWNsxF2KL9YRvIbbWg==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:mfodGlONo682alV9pnk4coGIHtRo3qMqjO6WqPtElTg=,iv:+QFrDXem90pGZIoyGFB79VLOcKD7UJU7s6xcUc7ENqw=,tag:sHxNeGrXoym1Dw6tnchn0g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:t3VvoQ==,iv:hqtrRaGBf2cpGxHlwITS41fTtBzJJsnXdnfC3rLe/5U=,tag:+UthpC0alyOhY/X7FUAyXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fv2r9xcluc5vnp4l8yg5amr95ar2vaencq5mddfead9lmrjx8fpqc8994x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ3MyY3NhNGllZ0xlSFlS
            UWh4RGJMRTlGWEJmSWF5MkJtOG9iWHJyN2xjCkRzY0kyZ1g0RGxBckhtUmoxRVA1
            T1BHTGNiRjBZV202YUZmUzFLUjE5R1UKLS0tIDhTcFdPc1AzZk5TMWJpeGZ2K01C
            RVVmRi83cXNTY3RkQ1Foa2UvOUQ1Q3MKBnyju/3kbq9+74xqyaQqMbV77hIBJq0m
            mXhvx+cNvERyWFQSHZGNBIvLpY4f0TaBSkmj7GfZBX5fc5Gweu+lWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-07T13:02:01Z"
    mac: ENC[AES256_GCM,data:BbOSTfKS0BQU9CiTMwc+WsftjixoWSV6FrdyYdxa5grR4ZCt6uiAGzNVEkshEohkEbB7Bc/V2gRm3lX4FevSRftdNdsUjE55CnDGh9HLNx5CYVtIMyy0zvDoUpkIWCiv/EJ17vSBodpjLVMF8Xy5O5/WJOKdDuceBdNlE5Jfuaw=,iv:UWhKxe4doqJ6Yxb8fX6Fuj2wsar+NR8wf4mdTGWEG3U=,tag:+ej8SOJD/p4MgY/pjL3ofA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
