---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.7.5604-980a13e02
    env:
      TZ: "${TIMEZONE}"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "plex-tls"
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        mountPath: /media
        accessMode: ReadWriteOnce
        size: 1Gi
      backup:
        enabled: true
        mountPath: /config/Backups
        accessMode: ReadWriteOnce
        size: 1Gi
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 1000Mi
