---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: librespeed
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: librespeed
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/librespeed
      tag: version-5.2.4
    env:
      TZ: "Australia/Melbourne"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "web"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "librespeed.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "librespeed.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 1000Mi
