---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: omada-controller
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: mbentley/omada-controller
      tag: "4.4"
    env:
      TZ: "Australia/Melbourne"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "router-network"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "omada.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "omada.${SECRET_DOMAIN}"
            secretName: "omada-tls"
    startup:
      spec:
        failureThreshold: 60
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 1000Mi
# Ports from https://community.tp-link.com/en/business/kb/detail/362
    service:
      main:
        type: "LoadBalancer"
        http:
          port: 8043
          protocol: HTTPS
        httpOther:
          port: 8048
          protocol: HTTP
          primary: false
        discovery1:
          port: 29810
          protocol: UDP
          primary: false
        discovery2:
          port: 29811
          protocol: TCP
          primary: false
        discovery3:
          port: 29812
          protocol: TCP
          primary: false
        discovery4:
          port: 29813
          protocol: TCP
          primary: false
        Initialization1:
          port: 27001
          protocol: UDP
          primary: false
        Initialization2:
          port: 27002
          protocol: TCP
          primary: false
    persistence:
      config:
        enabled: true
        mountPath: /data