---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.20.0
      sourceRef:
        kind: HelmRepository
        name: pihole-server-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "${TZ}"

    DNS1: 1.1.1.1
    DNS2: 8.8.8.8
    admin:
      existingSecret: "pihole-password"

    serviceWeb:
      loadBalancerIP: "${SVC_PIHOLE_ADDRESS}"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceDns:
      loadBalancerIP: "${SVC_PIHOLE_ADDRESS}"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        hajimari.io/enable: "true"
        hajimari.io/icon: "router-network"
      type: LoadBalancer

    persistentVolumeClaim:
      enabled: true

    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 200Mi
