---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole 
      version: 2.5.3
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "Australia/Melbourne"

    DNS1: 1.1.1.1
    DNS2: 8.8.8.8
    
    serviceWeb:
      loadBalancerIP: 192.168.1.11
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    serviceDns:
      loadBalancerIP: 192.168.1.11
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
        hajimari.io/enable: "true"
        hajimari.io/icon: "router-network"
      type: LoadBalancer
    
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 500Mi
