# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:WhwLBH08dAs65splELHxy72bwLBZuQEiYkJUzMcmLOVcxaChAg==,iv:4zH2h9/LZouLnwe7ATPUahdOzMb6V2gHq9fkvyDrPKI=,tag:uo1UtP4O1VVYYiJZbDm9Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fv2r9xcluc5vnp4l8yg5amr95ar2vaencq5mddfead9lmrjx8fpqc8994x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWjBLc3lFanQzWmRkYnhM
            b2ZWeHdDSlRpYTdYendtTXo4ZWNlVFg5Q0RRCkZZN0ErNE5RUEN3YlhiazgweGRI
            L3UvMTlrU3Bjbll1ekNyUTdQNDRTNWsKLS0tIDRtWkdDMlpjdU5ZdVV6Q1J6b0xt
            blNzZnZONjZjMUMxaE42TzhOQ2cxNzgKPw9ucy3+OVJbYmng7h+kSTiby2AfofMi
            qK4NaQeZY7bwz2PtmgezXbk5obuglsQZszREp16i/6SS//YwqtUTxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-07T11:59:39Z"
    mac: ENC[AES256_GCM,data:KiqTMYUAUBrq/l6Aev9NBKh1T5lUYHC1xFYqR9utfQb5O6VAjKNZ2IXlixu+CwFQBfRKV52FTQWB7PrINHDwfbY1gK8WCmBEeBDSGKWsHIuFz9D2bAjNsTzxk2ychYO25iM9jy+0yItzZm8tgfN4zrkwX+vt7XrL1iP8fNkpT0w=,iv:1RggXO93QiBX85JKosNf5dHQo7sIIdbd2b2MUiRC5Vo=,tag:Q9YoIvU+6OFa+eLVQbngvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
